<a href="https://colab.research.google.com/github/MohitDhungana/duplicate_question_detection/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
my_list=[1,2,3,4,5]

In [0]:
my_list

[1, 2, 3, 4, 5]

my_list[2]

In [0]:
import numpy as np

In [0]:
np_array=np.array(my_list)

In [0]:
type(np_array)

numpy.ndarray

In [0]:
np_function=np.arange(2,7,2)

In [0]:
np_function


array([2, 4, 6])

In [0]:
type(np_function)

numpy.ndarray

In [0]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [0]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [0]:
np.linspace(0,11,4)

array([ 0.        ,  3.66666667,  7.33333333, 11.        ])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.random.randint(5)

3

In [0]:
np.random.randint((3.4))

0

In [0]:
np.random.randint(1,10,5)

array([2, 7, 9, 4, 4])

In [0]:
np.random.seed(4)
np_arr=np.random.randint(1,100,15)

In [0]:
np_arr

array([47, 56, 70,  2, 88, 73, 51, 10, 59, 95, 56, 56, 58, 37, 51])

In [0]:
np_arr.max()

95

In [0]:
np_arr.min()

2

In [0]:
np_arr.mean()

53.93333333333333

In [0]:
np_arr.reshape((5,3))

array([[47, 56, 70],
       [ 2, 88, 73],
       [51, 10, 59],
       [95, 56, 56],
       [58, 37, 51]])

In [0]:
-np.sort(-np_arr)

array([95, 88, 73, 70, 59, 58, 56, 56, 56, 51, 51, 47, 37, 10,  2])

In [0]:
np_arr[2:9:1]

array([70,  2, 88, 73, 51, 10, 59])

In [0]:
np_array=np.random.randint(1,100,(10,10))

In [0]:
np_array

array([[45, 39, 53,  4,  1, 56, 22, 22, 74, 39],
       [57, 67, 47, 31,  9, 50, 67, 59, 88, 33],
       [41, 43, 46, 34, 33, 29,  4, 80, 99, 96],
       [58, 51, 18, 82, 90, 74, 60, 49, 77, 24],
       [95, 23, 68, 63, 63, 76, 24, 57, 71, 72],
       [74, 83, 56, 54, 86, 95, 80, 37, 92, 60],
       [52,  9, 38, 73, 60, 55, 97, 31,  5, 55],
       [76,  9, 32, 41, 18, 79, 10, 54, 69, 63],
       [60,  4,  5, 40, 55, 71, 41, 97, 68, 54],
       [23, 18, 28, 98, 61, 44, 87, 16, 14,  1]])

In [0]:
np_arry=np.random.randint(1,100,(16,1))

In [0]:
np_arry


array([[11],
       [ 8],
       [64],
       [80],
       [60],
       [53],
       [53],
       [65],
       [88],
       [98],
       [47],
       [43],
       [50],
       [32],
       [36],
       [31]])

In [0]:
np_rearry=np_arry.reshape((4,4))

In [0]:
np_arry[np_arry>50]

array([64, 80, 60, 53, 53, 65, 88, 98])

In [0]:
np_rearry

array([[11,  8, 64, 80],
       [60, 53, 53, 65],
       [88, 98, 47, 43],
       [50, 32, 36, 31]])

In [0]:
np_rearry[np_rearry>50]

array([64, 80, 60, 53, 53, 65, 88, 98])

In [0]:
col=[]
for i in range(0,len(df)):
    if df['color']==0:
        col.append('r') 
    else:
        col.append('b') 
plt.scatter(df['length'],df['width'],s=10,c=col[i])